/**/controller_manager:
  ros__parameters:
    update_rate: 300

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

/**/effort_controller:
  ros__parameters:
    joints:
      - joint_1_1
      - joint_1_2
      - joint_1_3
      - joint_1_4
      - joint_2_1
      - joint_2_2
      - joint_2_3
      - joint_2_4
      - joint_3_1
      - joint_3_2
      - joint_3_3
      - joint_3_4
      - joint_4_1
      - joint_4_2
      - joint_4_3
      - joint_4_4
      - joint_5_1
      - joint_5_2
      - joint_5_3
      - joint_5_4

/**/joint_state_broadcaster:
  ros__parameters:
    update_rate: 300
    joints:
      - joint_1_1
      - joint_1_2
      - joint_1_3
      - joint_1_4
      - joint_2_1
      - joint_2_2
      - joint_2_3
      - joint_2_4
      - joint_3_1
      - joint_3_2
      - joint_3_3
      - joint_3_4
      - joint_4_1
      - joint_4_2
      - joint_4_3
      - joint_4_4
      - joint_5_1
      - joint_5_2
      - joint_5_3
      - joint_5_4
