/**/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dg5f_s_15dof_right_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/**/dg5f_s_15dof_right_controller:
  ros__parameters:
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_nonzero_velocity_at_trajectory_end: false
    allow_partial_joints_goal: true

    joints:
      - joint_1_1
      - joint_1_2
      - joint_1_3
      - joint_2_1
      - joint_2_2
      - joint_2_3
      - joint_3_1
      - joint_3_2
      - joint_3_3
      - joint_4_1
      - joint_4_2
      - joint_4_3
      - joint_5_1
      - joint_5_2
      - joint_5_3

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

/**/joint_state_broadcaster:
  ros__parameters:
    update_rate: 100
    joints:
      - joint_1_1
      - joint_1_2
      - joint_1_3
      - joint_2_1
      - joint_2_2
      - joint_2_3
      - joint_3_1
      - joint_3_2
      - joint_3_3
      - joint_4_1
      - joint_4_2
      - joint_4_3
      - joint_5_1
      - joint_5_2
      - joint_5_3
